### ISSUE TITLE
Make it a woman or gender neutral

### ISSUE THREAD

**Issue by levino** [JushBJJ/Mr.-Ranedeer-AI-Tutor#19]
Why is this tutor a "man"? I think that is unnecessary since it actually is a genderless machine producing all the output. How about a gender neutral first name instead of "Mr." oder "Mrs."?

**Comment by pepeto** [comment]
The only Mrs. is Mrs. Pac-Man.

**Comment by JushBJJ** [comment]
lol

**Comment by levino** [comment]
Very clever. Killing your project for brogrammer jokes. But it is your project after all.

**Comment by MRQJsfhf** [comment]
Facts aside, why not define Chait AI gender as a cash register at Walmart, while I think the AI instructor is a transgender, and the psychological gender of the AI teacher should be the lava in Hawaii.😁
