### ISSUE TITLE
Typo in README: Incorrect Number of Tokens for Markdown Prompt

### ISSUE THREAD

**Issue by EmileDqy** [JushBJJ/Mr.-Ranedeer-AI-Tutor#29]
## Issue Summary

Hello, I found a small typo in your project's readme file. The Markdown version of the prompt is said to be 1280 tokens, but it is actually 1820 tokens, which is somewhat misleading.

## Proof

Please see the attached screenshots for proof of the actual number of tokens in the Markdown version of the prompt:

![Screenshot 1](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/assets/4007819/710f4520-02f9-425e-8cb1-7b166fa66d48 "Screenshot 1")

As you can see, the actual number of tokens is 1820, not 1280.

This means that the reduction from the JSON format to the Markdown version is not 3x, but rather 2.14x, as shown in this screenshot:

![Screenshot 2](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/assets/4007819/4739a9a7-cda4-4f7b-b8a4-36780f07d587 "Screenshot 2")

Thank you for your attention to this matter. Have a nice day.

**Comment by JushBJJ** [comment]
Fixed
https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/commit/3bd1157008b44dc8456cb02e556061fdb6cf8914
