### ISSUE TITLE
Add an interactive mode to choose preferences

### ISSUE THREAD

**Issue by jsolly** [JushBJJ/Mr.-Ranedeer-AI-Tutor#33]
## Context 
I am not super familiar with what reasoning framework I would prefer along with some of the other settings. I did [read the docs](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/blob/main/docs.md) but I still don't really know which one to choose.

## Current Behavior/Workaround
I asked Chat to ask me questions to narrow down what setting to choose
![image](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/assets/9572232/4009f81b-8ed5-4655-ad69-865f2bd09ec8)

## Ideal behavior
There should be a 'wizard' workflow that helps the user decide what settings to use.

**Comment by JushBJJ** [comment]
I would love to add a config wizard, but due to the current 25 message limit + 8k token limit, I don't think its necessary at the moment. So I'm keeping this open and putting it on the GPT-4-32k milestone

**Comment by JushBJJ** [comment]
Here's an idea, we could create a specialized prompt running on GPT-3.5 to act as a Configuration Wizard, users would be directed to the direct Wizard link if they do the `/config` command.

**Comment by JushBJJ** [comment]
Closed https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/pull/72 - Added Config Wizard

**Comment by jsolly** [comment]
Hey thanks for adding that @JushBJJ. It's looking really good.
