### ISSUE TITLE
Credits for you JushBJJ

### ISSUE THREAD

**Issue by angelkurten** [JushBJJ/Mr.-Ranedeer-AI-Tutor#36]
I created an OKR Assistant called Mia Kürten, in the readme I added a section for giving credits to you @JushBJJ 

https://github.com/angelkurten/Mia-Kurten-AI-OKR-Assistant

Context: I'm an Engineering Manager and I have 25 devs on my team, this assistant is helpful in my work

**Comment by JushBJJ** [comment]
Thanks! Make sure to checkout bleeding edge Mr. Ranedeer here: https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/tree/testing
