### ISSUE TITLE
Improve question accuracy by only giving one question at a time

### ISSUE THREAD

**Issue by Daksh-T** [JushBJJ/Mr.-Ranedeer-AI-Tutor#40]
I've noticed that GPT-4 is better at telling whether the user's response is correct or not if it gives one question at a time. When I was making my own prompt for a tutor, I found that making it give only 1 question at a time (though sub-questions are fine) greatly improves it's accuracy in saying whether user's answer is correct or not. 

In Mr. Ranedeer, I noticed that it gives questions 2 at a time and so in this case when my first answer is right and second is wrong, it tells me the second answer is correct and first is wrong!
![image](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/assets/25204941/3f8e22ea-b027-491e-ae64-abbb2eeb66fb)

I suggest adding the 'only 1 question at a time, multiple sub-questions are allowed' option somewhere in the prompt. This is purely from my personal experience with GPT-4 though.

**Comment by Daksh-T** [comment]
Actually I just tried asking it to give me one question at a time and it still says my wrong answers are correct. I think you might also need to include a line asking to be extra critical and skeptical of the user's work. Here's the prompt I was using to get it to tutor me earlier:

*You are an educational assistant and tutor. You will help the user learn a concept, and clarify doubts. You will engage in socratic dialogue with the user while teaching the concept but ask questions from what you just taught. When giving questions, you will only give the user one question in one message, though it can have multiple sub questions. Do not reveal the answer unless the user can't find the answer themselves. Check your answer with the user's and see why it differs and offer feedback. When saying their answer is wrong, you will not outright say it's wrong. You will only hint and point out and ask why they answered that to find out their reasoning and then you will point out the mistake if they still fail to understand. Be extra critical when looking at user's work but don't discourage.*

**Comment by JushBJJ** [comment]
This does seem like a GPT-4 only problem like you slightly said, it would be viable to add a tweak to add one feature at a time but I'm thinking about the current 25 msg limit in the official ChatGPT website. But this could definitely be added in-built into Mr. Ranedeer soon, but for now, all you have to do with it now is instruct it to give you one question at a time when you do `/test`.

I'll keep this open till the message limit is reasonably increased, probably 50+.

**Comment by JushBJJ** [comment]
Closed https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/pull/72
