### ISSUE TITLE
Suggestion: Use the new "Shared Link" feature to make getting started even easier

### ISSUE THREAD

**Issue by varenc** [JushBJJ/Mr.-Ranedeer-AI-Tutor#44]
OpenAI has added a a new [share link](https://help.openai.com/en/articles/7925741-chatgpt-shared-links-faq) feature to ChatGPT that lets you share a conversion and, importantly, let others continue the conversion in their own private session. With this, you can cut out the copy+paste step of getting started with Mr Ranedeer!

For example: https://chat.openai.com/share/5c2850c0-1ce9-456b-9ca0-44faf40ec2bf

After heading there just click "Continue this conversation" to pick up the conversation and configure the tutor in your own private session. This could be used to help others get started near-instantly without having to find a file on GitHub and copy and paste the large blob of text.

**Comment by JushBJJ** [comment]
**IMPLEMENTING IMMEDIATELY**

**Comment by JushBJJ** [comment]
YOU'RE A GENIUS

**Comment by JushBJJ** [comment]
https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/blob/main/README.md#preloaded-conversations-v25

**Comment by varenc** [comment]
Yay! I love it. Also you win my personal award for the fastest response time on a github project ever. (though sorry it looks like the Shared Link feature on ChatGPT isn't quite ready for prime time yet)
