### ISSUE TITLE
Iterative Planning and Lesson & Ladder Plan Hype!

### ISSUE THREAD

**Issue by JPili** [JushBJJ/Mr.-Ranedeer-AI-Tutor#46]
I'm super looking forward to the Iterative Planning and Lesson and Ladder Plan features! The potential for them to give us high-quality complete tutorials for absolutely any topic is unbelievably exciting.

**Comment by JushBJJ** [comment]
I will not let you down.

**Comment by JPili** [comment]
Haha, thanks! You're doing absolutely amazing work.

I hope this eventually gets made into a full-fledged app. Lots of people would almost certainly be willing to pay for a much more streamlined learning process.
