### ISSUE TITLE
I click this link，and OpenAI give me 404

### ISSUE THREAD

**Issue by yangyang8599** [JushBJJ/Mr.-Ranedeer-AI-Tutor#56]
![image](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/assets/14066163/77bc3ada-a4f4-42ea-aad6-3814238da295)

**Comment by yangyang8599** [comment]
the link is https://chat.openai.com/share/3946ee70-fb09-406e-8ed1-0ee756e4411f

I found it in the page of [JushBJJ](https://github.com/JushBJJ)
/
[Mr.-Ranedeer-AI-Tutor](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor)

**Comment by Cerf-Volant425** [comment]
Me too.

**Comment by AHANAyl0n** [comment]
+1

**Comment by JushBJJ** [comment]
Fixed. Sorry guys I cleared my chat history because it was messy, didn't think about the consequences 😂
