### ISSUE TITLE
Getting 404 using the template

### ISSUE THREAD

**Issue by inquiloper** [JushBJJ/Mr.-Ranedeer-AI-Tutor#68]
I have chat gpt plus. After trying to use this link: https://chat.openai.com/share/378699b4-e3d0-436d-a789-4e6844f76319 and clicking continue, it gives me a 404.

**Comment by JushBJJ** [comment]
Investigating

**Comment by JushBJJ** [comment]
Looks like it was a bug in OpenAI's end, the link has now been updated.

https://chat.openai.com/share/19a00eef-9e52-4d80-81d6-9c70cd873d7d
