### ISSUE TITLE
example: Execute <config-example> is redundant

### ISSUE THREAD

**Issue by finsterniz** [JushBJJ/Mr.-Ranedeer-AI-Tutor#69]
if say "/example", i get:
"""
I'm sorry, but the "/example" command is not in my current list of features. But I will try to help. If you have any other commands or questions, feel free to let me know.
"""

**Comment by JushBJJ** [comment]
Closed https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/pull/72 - Should be fixed now, let me know

**Comment by finsterniz** [comment]
already solved👏
