### ISSUE TITLE
Typo in prompt 'Casual' for 'Causal'

### ISSUE THREAD

**Issue by irl-dan** [JushBJJ/Mr.-Ranedeer-AI-Tutor#7]
typo in the prompt json:

```
                    "Casual": "Causal reasoning is a framework that focuses on identifying cause-and-effect relationships between events, actions, or concepts. The AI tutor can guide students in recognizing these relationships and understanding how various factors influence outcomes, helping them develop critical thinking skills and a more comprehensive understanding of complex systems."
```

`Casual` key should be `Causal`

Could very well could slightly distort pure "causal" reasoning into "casual" reasoning which is definitely different lol.

**Comment by medic-code** [comment]
This has now been fixed [here](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/commit/1a3980bd0e4890152a56bfbfc93c0dcabff5658e)

Close issue?
