### ISSUE TITLE
Markdown prompt

### ISSUE THREAD

**Issue by FilJed** [JushBJJ/Mr.-Ranedeer-AI-Tutor#70]
Hi!

There was great Mr. Ranedeer markdown promt, that takes minimum tokens.
Why did you remove it? Is it possible to get it?
Thanks in advance!

**Comment by JushBJJ** [comment]
The reason why I removed markdown is because I wanted to clean up the prompt more into a less token-usage (against the JSON format specifically) and I wanted to evolve the style ChatGPT Mr. Ranedeer is built on.
