### ISSUE TITLE
Error searching knowledge

### ISSUE THREAD

**Issue by hroyhong** [JushBJJ/Mr.-Ranedeer-AI-Tutor#85]
**Describe the bug**
Whatever I tell the GPT, he gives me the report of "Error searching knowledge" "It seems there's an issue accessing the files"

**To Reproduce**
1. Go to the gpt
2. Ask him to do anything
3. See error

**Expected behavior**
There's supposed to be no Error and I should have been able to configure.

**Screenshots**
<img width="647" alt="截屏2023-12-26 13 42 06" src="https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/assets/41256591/27a3089b-4ee3-4470-8976-f5187ae8697b">

**Comment by JushBJJ** [comment]
Fixing...

**Comment by JushBJJ** [comment]
Fixed, all I did was reupload the files. Weird...
