### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by ShinyChan159** [JushBJJ/Mr.-Ranedeer-AI-Tutor#87]
The link you provided could not be opened and displays 404

**Comment by JushBJJ** [comment]
That is super weird

**Comment by JushBJJ** [comment]
@ShinyChan159 Do you have ChatGPT Plus?

**Comment by ShinyChan159** [comment]
Yes，I have ChatGPT Plus.
This is a strange problem and I can only solve it by copying the code and creating it myself.

**Comment by JushBJJ** [comment]
I just republished the GPT, can you try again?

Try the one in the README, then this one:
https://chat.openai.com/g/g-9PKhaweyb-mr-ranedeer

Let me know if anything is different

**Comment by ShinyChan159** [comment]
It's OK Now

**Comment by JushBJJ** [comment]
Nice, thank you for raising the issue :D
